### ISSUE TITLE
Hunting down missing MacOS Dock icon bug. Pointers appreciated!

### ISSUE THREAD

**Issue by tjg** [quil/quil#158]
I read the FAQ and realize it's a known problem. :)

I tried setting `"apple.awt.UIElement"` Java property to `"false"`. Doesn't seem to work.

Does anyone have a vague idea what's going on? Is this within Processing? Or might I find luck trying to debug this in the Clojure lib?

I'd like to know possibilities people already eliminated, to save me time. Thanks!

**Comment by Norgat** [comment]
Quil using ```Processing.PApplet``` class for running sketches on desktop (because ```Processing.PApplet``` contains some hacks for GUI problems for OS X and we don't want to maintain those hacks).

Quil code for running applet: 

https://github.com/Norgat/quil/blob/master/src/clj/quil/applet.clj#L439
https://github.com/Norgat/quil/blob/master/src/clj/quil/applet.clj#L77

So, ```quil.Applet``` inherited from ```processing.core.PApplet``` and call ```runSketch``` method.

I guess that you can explore what needed to adding support of dock icons and propose patch for it.

**Comment by tjg** [comment]
Thanks @Norgat!

For ClojureBridge, I think I'll just advise learners to use `:features [:keep-on-top]`. For anyone morbidly interested, these didn't work yet:
- Avoiding `JAppleMenuBar` didn't work.
  - Tried reflection to set
  `japplemenubar.JAppleMenuBar.instance.setVisible(true, false);`.
  - Set `PApplet.platform = PConstants.WINDOWS;` to avoid `japplemenubar.JAppleMenuBar.instance.setHide();`.

- Embedding the java.awt.Canvas into another app seems nontrivial: [docs are unclear](https://github.com/processing/processing/blob/dea1d58e918765808c82d6f1cc9413dd23954971/core/src/processing/core/PApplet.java#L91), and [so is the code](https://github.com/processing/processing/blob/dea1d58e918765808c82d6f1cc9413dd23954971/core/src/processing/core/PApplet.java#L9872).

**Comment by nbeloglazov** [comment]
For teaching purposes you can also try ClojureScript version of Quil. Since 2.2.6 quil supports live reloading if you're using plugins like figwheel to dynamically reload code as you modify it. This way there shouldn't be any macos-specific surprises as you'll be using chrome/firefox/safari which Quil equally supports.

**Comment by tjg** [comment]
Thanks @nbeloglazov, I'll try the ClojureScript version out!
