### ISSUE TITLE
Draw continuous squiggle from mouse input?

### ISSUE THREAD

**Issue by NathanSmutz** [quil/quil#163]
Is there an established way to let someone draw a continuous squiggle from a mouse or  a touch-screen?
Drawing dots, it appears that the mouse isn't polled often enough and you get breaks in fast movements.  I tried to connect detected mouse-locations with lines.  I modified your basic fun-mode example, using a :mouse-dragged function to load the state with the start and end points of the drag.   I had thought that the "previous point" reported in the mouse-dragged event (:p-x and p-y) would match the current point (:x and :y) of last polled location (the end of the previous line), so you could draw lines between the gaps in polled mouse points. However, even though the button isn't released, this still results in a series of lines with spaces between them.

I suppose you need to manuall track mouse-down/up, to draw a continuous squiggle.  Is there a best or standard way to do this?

**Comment by nbeloglazov** [comment]
Hi Nathan

Yes, I believe the best way to draw squiggle is to use `mouse-moved` or `mouse-dragged` events. And "previous point" should match current point of last polled location. Here is an example of a sketch that draws connecting line from mouse-dragged event: 
http://quil.info/sketches/show/8FoquKaDzP (you can run from the browser)

Also if you want to save coordtinates of the squiggle - you can simply have a collection of all points in state and append a new point on each mouse-dragged event. In `draw` function you simply draw squiggle using all points:
http://quil.info/sketches/show/LjeyT85ye8

In both cases I don't see gaps between lines and everything looks quite smooth. Is it possible that there is a bug in your implementation? Like if you in `mouse-dragged` event you store current and previous points to state and `draw` draws a line between them . What happens if `mouse-dragged` called twice before `draw` is called?

**Comment by NathanSmutz** [comment]
That did the trick.  I didn't realize fun-mode allowed drawing from the mouse-dragged function.  I think you're right about multiple mouse events overwriting a single-map state before the draw funciton could execute.

**Comment by nbeloglazov** [comment]
Glad I could help! Closing the issue. Feel free to reopen it if you have additional questions or ask on "clj-processing" google group.
