### ISSUE TITLE
quil.core/stroke-cap has no effect with ClojureScript

### ISSUE THREAD

**Issue by jbaiter** [quil/quil#170]
Setting the stroke caps to a value other than `:round` doesn't seem to have any effect with the ClojureScript backend.

Example:

```
(ns foo/example
  (:require [quil.core :as q :include-macros true]))

(defn setup []
  (q/frame-rate 30))

(defn draw []
  (q/background 255)
  (q/stroke 0)
  (q/stroke-cap :square)
  (q/stroke-weight 10)
  (q/no-fill)
  (q/line 200 200 250 250))

(q/defsketch foo
   :host "canvas"
   :size [500 500]
   :setup setup
   :draw draw)
```
http://quil.info/sketches/html/3LwVjuOYwz

**Comment by nbeloglazov** [comment]
Indeed. Thanks for reporting and providing good reproducible example, that helped! Apparently some processingJs functions use values constants instead of ints while we expected only ints (like in regular processing). Actually processingJs source [claims](https://github.com/processing-js/processing-js/blob/master/src/Processing.js#L6476) it takes int values (but in fact they're string) which adds to confusion. 

Also thanks to your report `stroke-join` and `cursor` were fixed as well.
