### ISSUE TITLE
clojurescript interface is not very repl-friendly

### ISSUE THREAD

**Issue by jaredly** [quil/quil#176]
If you try out any function outside of an applet context -- even ones that have nothing to do with drawing (like `q/abs`) -- it errors with "cannot read property 'abs' of null". Is there a way to make it so such utility functions don't depend on `(current-applet)`?

**Comment by GoToLoop** [comment]
Dunno Clojure; but in Java outside ***PApplet*** class context, as a _".java"_ suffixed tab, in order to access any `static` method like **abs()**, we just prefix it w/ the name of its class: `PApplet.abs(PConstants.MIN_INT);`

**Comment by Norgat** [comment]
We need know current-applet because it contains html canvas contex (we can't draw without it).
All quil math functions inherite this behaviour from Processing.js

Do you try use https://github.com/quil/quil/blob/master/src/cljs/quil/sketch.clj#L3 ?
I add it for calling code in sketch context.

**Comment by GoToLoop** [comment]
I wonder which _"processing.js"_ version Quill/ClosureScript is using?

**Comment by Norgat** [comment]
@GoToLoop I think that this is the answer for your question: https://github.com/quil/quil/blob/master/project.clj#L18

**Comment by GoToLoop** [comment]
* Thx @Norgat, processing-js "1.4.8.2". As I had feared...
* The last ".2" much probably means some sub-fork I believe.
* Pjs 1.4.8 was the last release which allowed it to be used as a pure JS library.
* The whole feature was removed unannounced (no debate & no release notes at all).
* And only found out much later by chance: https://github.com/processing-js/processing-js/issues/192
* Moreover, Pjs can't be used by transpilers anymore like ClojureScript, CoffeeScript, TypeScript, etc.
* I conclude Quill project is stuck w/ Pjs 1.4.8 just like CoffeeScript Mode is too:
https://github.com/fjenett/coffeescript-mode-processing
* B/c they need to transpile to JS syntax rather than keep a Java-ish syntax! Alas...

**Comment by nbeloglazov** [comment]
Yes, non-repl friendly is a known problem. In clojure (which uses java Processing) methods like `abs` or `sin` are static methods so you can use them without instance of applet. But in clojurescript all methods, like @Norgat mentioned, are instance methods so you have to have an applet. 

Jared, what kind of repl development do you have in mind with Quil where you want to call functions without applet? So I can better understand how we can improve interface.

**Comment by nbeloglazov** [comment]
@GoToLoop that's unfortunate. I had plans to upgrade processing.js dependency to latest :(  I think I'll try it anyway to see if it really so bad. Maybe it's not officially supported but still works with some jumping through hoops.

**Comment by jaredly** [comment]
@nbeloglazov here's the (wip) repl http://jaredforsyth.com/tutorial-cljs/
I've hacked it so that you can access the most recently created applet from the REPL, by just doing `(set! quil.sketch/*applet* the-applet)` :D so you can call the drawing functions too!

**Comment by nbeloglazov** [comment]
I see. Yes, that's a workaround. Though quil was designed with having "draw" function that does draw commands inside it and invoked many times per second. Instead you introduce another approach where nothing is being redrawn and instead you call drawing functions separately and their result is stored and not cleared. But I think at the end, if you want to use quil, you still need to go back to "everything inside 'draw' function" approach and this switch maybe confusing because user already got used to "just call any drawing function anywhere and it results stays". 

Also cool tutorial! Is it cljs-in-cljs? I tried to set it up for http://quil.info/sketches/create but failed. Currently it uses server-side cljs compilation. How hard is it to add cljs-in-cljs support for quil.info do you think?

**Comment by jaredly** [comment]
yup! it uses [replumb](https://github.com/ScalaConsultants/replumb) which gets some of the more confusing configuration out of your way. I'd be happy to help w/ any issues you run into -- I ended up doing a fair amount of digging into the internals

**Comment by hamoid** [comment]
I believe such eval-to-paint technique is powerful for teaching. You eval a call to line, and you see a line. It was one of the first things I asked when I started with Quil: https://twitter.com/hamoid/status/697431375230713860

**Comment by heyarne** [comment]
I know this issue is pretty old, but is there a similar technique for the Clojure version as well? I'm running the sketch from within emacs and I would love to be able to poke around in my front-most applet or something like that.

**Comment by nbeloglazov** [comment]
When running on emacs I usually change and reevaluate the whole `draw` function. This approach doesn't fit your needs?

**Comment by heyarne** [comment]
It does in general and it's great to change the running sketch. However I'm still new to Processing / Quil / Clojure, so I make mistakes sometimes and as I said in the other issue: Doing many stupid things in a short timespan causes hiccups (meaning sometimes it's very heavy on the cpu, sometimes it causes emacs to hang and crash...).

I feel if I had something like

```
(q/with-sketch my-sketch
  (for [x (range xs) y (range ys)] (q/noise x y)))
```

that I could just execute in the repl (or directly in the clojure buffer) and see what values it returns that would help a lot.
