### ISSUE TITLE
I would like to use a Processing library. How easy would quill be to extend with this library

### ISSUE THREAD

**Issue by SlightlyCyborg** [quil/quil#184]
Specifically, I want the ability to load and play/loop animated gifs using https://github.com/extrapixel/gif-animation

**Comment by nbeloglazov** [comment]
This is related: https://groups.google.com/forum/#!topic/clj-processing/Fegk10gL4P8

Basically you need 
1. Somehow include gifAnimation library to your project. If it's already in maven somewhere - perfect, just add its coordinates to `project.clj`. Otherwise you might need to download it, upload to local maven repo using [`localrepo`](https://github.com/kumarshantanu/lein-localrepo) plugin. 
2. Familiarize yourself with java interop. As you're going to work with plugin - you have to use create java class and call methods on it. 
3. Translate example from gifAnimation readme to clojure. Check thread I mentioned above as example of similar translation. Basically you need to create instance of `Gif` object in `setup` function passing `quil.applet/current-applet` instead of `this`.

**Comment by nbeloglazov** [comment]
Added answer in FAQ: https://github.com/quil/quil/wiki/FAQ#how-to-use-processing-plugin Closing this issue. Feel free to reopen if you still have problems/questions.
