### ISSUE TITLE
Null Pointer with Quil/random 

### ISSUE THREAD

**Issue by Cynlic** [quil/quil#191]
Hey there, I couldn't find a fix for this in the other issues. It seems that q/random is returning a Null Pointer? Hope I don't come off as a buffoon, but I've got a (mostly)blank .core file
```
(ns testing.core
(:require [quil.core :as q]))

(defn setup [])

(defn draw-state []
  (q/background 240))

(q/defsketch testing
  :title "new"
  :size [500 500]
  :setup setup
  :draw draw-state)
```
Lein repl and enter into the correct namespace: 
```
user=> (ns testing.core)
nil
```

and voilà
```
testing.core=> (q/random 500.0)
NullPointerException   quil.core/random (core.cljc:3166)
```

I'm pretty lost as to what to do.

**Comment by Cynlic** [comment]
Also yes, I realize that I can use clojure's (random) func -- I just wanted to put this up here.

**Comment by nbeloglazov** [comment]
Hi Harrison. Most quil functions must be executed inside setup/update/draw or handlers because they need to know what "current sketch" is. `random` one of such functions: https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L3166 So it is working as intended. Generally quil is not very repl friendly: you cannot just run single quil function like `rect` or `line`. Instead you redefine the whole `draw` function:

```clojure
testing.core=> (defn draw-state [] (q/rect 0 0 100 100)
; rect is drawn
testing.core=> (defn draw-state [] (q/ellipse 0 0 100 100)
; ellipse is drawn
```

**Comment by Cynlic** [comment]
Ah! I realized after opening this issue that most of the quil functions didn't work in the repl but I hadn't thought of redefining the draw function in the repl itself. Many thanks for the tip.

**Comment by nbeloglazov** [comment]
You're welcome!
