### ISSUE TITLE
Why introduce update function for functional-mode? 

### ISSUE THREAD

**Issue by xfcjscn** [quil/quil#214]
I my opinion, function setup & draw both perform drawing work. 
If we can use function setup to manage state, why not function draw? 
Why we remove update function & let draw do the job?

**Comment by nbeloglazov** [comment]
The goal of functional mode is to separate computation part from "side-effect" part, which drawing. The process of drawing involves 2 steps that are often intermixed but in functional mode they are separate: the first is **what** to draw (prepare data required for drawing) and the second is **how** to draw (implementing functions that take that data and draw it). Personally it helps me to think about data without being distracted with drawing details. Another benefit of that separation is that `update` should ideally be pure function. Which means you can run it in repl to test and iterate. At the same time you can't run `draw` from repl because it has to be run "from" sketch. 

Having said that if you find it easier to combine them - you might find it easier using Quil without functional mode. Without functional mode you have only `draw` and no explicit state object. But it you need it - you can use either [state-atom](http://quil.info/api/state#state-atom) or even declare you own global atom variable and change it inside `draw`.

**Comment by xfcjscn** [comment]
Thanks.
