### ISSUE TITLE
Trouble getting output from q/save-frame

### ISSUE THREAD

**Issue by Vaguery** [quil/quil#220]
I've got a ClojureScript project (using latest versions across the board, and `fun-mode` if that makes any difference) working the way I would like. My plan is to save a frame every hundred ticks or so. But executing `(q/save-frame "filename-#####.png")` produces nothing, not even a slowdown.

I haven't stumbled across anything in the docs or closed issues that seems to indicate a problem with `save-frame` in ClojureScript, and it doesn't seem to be labeled Clojure-only. Am I missing something? Is there a trick I'm missing?

I've checked all the usual suspects, too: doesn't change when I switch from `lein figwheel` to `lean compile`, I'm definitely looking at the right compiled javascript, and there are no console entries indicating a problem.

**Comment by Vaguery** [comment]
Ah. Is `q/save-frame` not supported by ClojureScript? https://github.com/quil/quil/wiki/List-of-available-functions-in-ClojureScript

**Comment by nbeloglazov** [comment]
It kinda works. In ClojureScript you can't save sketch to a file because it runs in browser and you can't create files from js in browser AFAIK. What q/save or q/save-frame do instead is they conver image into base64 and open a new tab using encoded image as source:  https://github.com/processing-js/processing-js/blob/master/src/Processing.js#L8796

So each time you call save/save-frame it opens a new tab. In my case chrome blocks all these new tabs thinking it's spam. There is a small icon in page url bar on the right which says that pop up blocked. If you click you'll see all new tabs for each frame. And when you click on one of them it should open a tab with image of your sketch.

But probably it's not what you need anyway. If you want to generate images I think you have to use clojure version. Or do saving yourself somehow using js/server side.

**Comment by Vaguery** [comment]
Whew. I checked, and indeed the anti-spam settings in Safari were also blocking the new tabs.

But you're right; I should probably be maintaining a CLJ branch of my project to save movie frames to disk.
