### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by plotinus5** [quil/quil#222]
Hi,
When I try the given example, I have the following message that I don't understand. Could someone help me? Thank you.

user=> (use 'my-art.core :reload-all true)

CompilerException java.lang.UnsupportedClassVersionError: processing/core/PApplet : Unsupported major.minor version 52.0, compiling:(quil/core.cljc:1:1)

**Comment by nbeloglazov** [comment]
Hi. This error says that your java version is too old: https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0 Quil works only on jdk 1.8 since version 2.5.0: https://github.com/quil/quil/blob/master/RELEASE-NOTES.md#250

So you either have to update your jdk or use older version of quil.

**Comment by plotinus5** [comment]
Thank you!


Best,

Marcus.

________________________________
De : Nikita Beloglazov <notifications@github.com>
Envoyé : samedi 28 octobre 2017 21:53
À : quil/quil
Cc : Marcus Missal; Author
Objet : Re: [quil/quil] Error message (#222)


Hi. This error says that your java version is too old: https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0 Quil works only on jdk 1.8 since version 2.5.0: https://github.com/quil/quil/blob/master/RELEASE-NOTES.md#250

So you either have to update your jdk or use older version of quil.

-
