### ISSUE TITLE
com.lowagie.itext deprecated

### ISSUE THREAD

**Issue by jedahan** [quil/quil#224]
according to the website, been deprecated since 2012. I was able to remove it from the .pom in my repository in an attempt to use quil with java9/clojure 1.9.0, but some luck...

**Comment by nbeloglazov** [comment]
Does it cause any problems? We use that version of itext because it is used by Processing. I'd expect it to keep working in newer version of java/clojure.

**Comment by jedahan** [comment]
It has been giving me issues - it has a dependency on a jar that isn't on maven/clojars for java9 anymore. It seems to be useful for pdf generation, which means maybe we can make it optional? I need to look into processing-js and see if that runs on java9 / what needs to be done.

**Comment by nbeloglazov** [comment]
Hmm. I upgraded to java 9 and actually quil didn't work at all. I got exception due to Processing not correctly parsing java version. That's because Quil uses a little bit outdated version of processing. So I guess first order of business is to update Quil to use latest processing. Then I'll deal with java 9 compatibility. 

If you have suggestions for the dependency issue - please share. Also what error to you get?

**Comment by nbeloglazov** [comment]
Processing 3.3.7 was release a week ago and it's actually seem to be working with java 9. So I updated head Quil to use 3.3.7 and it ran without errors. I didn't the error related to com.lowagie.itext. Do you have error message or stack trace or something?
