### ISSUE TITLE
Support non-sketch use of drawing functions

### ISSUE THREAD

**Issue by lspector** [quil/quil#241]
Quil's drawing functionality is by far the best that I know of in the clj/cljs space, but at least for me and my students (who request this frequently) it is not obvious if/how it can be used from clj/cljs projects that cannot easily be packaged as a sketch with a draw loop. 

Queries and searches for ways to do this over the years have turned up helpful people with interesting suggestions but nothing fully worked out or within the abilities of many Quil users to fill out. 

It would fabulous for this to be addressed in some way by Quil insiders, either through code changes or just documentation if there are existing ways to do it. I have several projects that have been blocked for lack of a way to do this, my students have had many more, and I suspect that there is actually quite a large community of potential users who would benefit from this.

**Comment by nbeloglazov** [comment]
Hi Lee. Thanks for your feedback! Can you describe your usecase in more details? Is it using REPL and evaluating commands one by one like "draw rectange, hit enter, look at results, draw circle, hit enter look at results, call clear, ..."?

**Comment by lspector** [comment]
Here are a couple of use cases, all of which happen to involve genetic programming because I do/teach that a lot recently:

- I would like to use Quil functions to visualize progress of a run of my [Clojush](https://github.com/lspector/Clojush) genetic programming system as evolution proceeds. The run might be launched from a command-line call (`lein run ...`) rather than from a REPL, and that command-line might also include many other arguments that have to be handled by Clojush's `-main` function. At the end of each generation of the genetic programming process I would like to draw some lines and shapes to a window using Quil functions, showing what's happening in the genetic programming population, but it would not be easy to run the entire system from within a Quil sketch.

- I would like to augment the `interpret-program` function in my [Propel](https://github.com/lspector/propel) implementation of the Push language to take an `animate?` argument which, when `true`, causes a window to pop up and show an animation of the program being executed, showing all of the data stacks with items being pushed/popped/modified, much like the diagrams that I created by hand in [this presentation](https://www.youtube.com/watch?v=ryW9w5cAwaI&t=12s). I would like this to be available wherever `interpret-program` is called, which may be in an as-yet-unknown machine learning system which may not involve a Quil sketch.

- A student of mine recently wanted to use genetic programming to evolve images, and to present the images to the user for assessment during evolution. This would involve popping up a window, drawing to it, and then accepting user input of some kind. All of this can be handled quite nicely in Quil, but only if the entire system is created within a sketch, which may require that it be re-designed and re-written.

- A student of mine recently wanted to use genetic programming to evolve images, and wanted to use Quil's image processing functions as part of the automated "fitness" assessment process. His system had its own control structure that could not easily be reformulated to run within a Quil sketch, and he was unable to figure out how he could use Quil's functions in any other context.

More generally, both for scientific and artistic purposes, I have often found that I (or my students) have a pre-existing control structure that does not naturally fit within the structure of a Quil/Processing draw loop, and I would then like to add functionality that Quil so beautifully provides -- usually just drawing. I then seem to have just two options: 1) Re-think and re-write the whole thing to work within a Quil draw loop, which can often be quite involved, or 2) use some other library, but really there just don't seem to be any other good options, and certainly none with the ease of use and great visual control of Quil/Processing.

**Comment by nbeloglazov** [comment]
Thanks for the extensive examples! Really useful to better understand that context. I agree that Quil's sketch structure should not dictate the structure of the whole program when sketch is not the main part of the program. And I believe it's possible to use Quil in that way without major changes to the library. 

When I think about such cases I mentally split the program into 2 parts: main algorithmic part and visualization (Quil). Naturally it's easier to interleave algorithm and drawing parts of program. For example if I want to implement and visualize Dijkstra algorithm I might implement it like 

1. Find next node.
2. Update its neighbors.
3. Redraw state. 

This is not easy with Quil as you mentioned, because you can't just "redraw" something outside of sketch. So instead I'm using slightly different approach: I treat Quil as a separate subprogram that interacts with the main algorithmic part of the program via some interface. Simplest kind of the interface between Quil and main part would be a mutable object, atom: when the main program runs, it updates the state. Quil sketch is running in parallel and constantly redraws the state. Trivial example of such interaction is progress bar:

```clojure
(ns progress-bar
  (:require [quil.core :as q]))

(defn draw-progress [progress]
  (q/background 255)
  ; Drawing progress as text
  (q/text (str "Done " progress "%") 100 100))

(defn start-progress-bar [state]
  (q/sketch
    :size [200 200]
    :draw #(draw-progress (:progress @state))))
```

Now you can call `start-progress-bar` function passing an atom that contains map `{:progress 0}`. Main program changes the progress key to some number and sketch redraws it. 

Naturally state can be more complex than that. For example it might contain data stacks from Push. Similarly you can add feedback capability by passing listeners to the function that creates sketch. For example for the Push animation you might want handle to handle "space" key as "execute next command":

```clojure
(defn animate-push-program [state trigger-next-command-fn]
  (q/sketch
    :size [500 500]
    :draw (draw @state)
    :key-pressed #(when (= (q/key-as-keyword) :space)
                    (trigger-next-command-fn))))
```

This approach forces you to think about the interface between the main program and animation. Which  is probably annoying when you need to create simple animation but as soon as main program becomes non-trivial you need to think about it anyway. Also it helps to keep animation separate from the main program which is kinda cool and allows to swap animation implementation. Of course assuming that interface is generic enough. 

In somewhat similar vein few years ago I created a multplayer snake game in clojure. Logic that updates the world runs on server. Clients implemented using quil. When new client connects to the server then the server starts sending world state updates to the client. On client there is a Quil sketch which only role is to draw world when new version is received. [code](https://github.com/nbeloglazov/snakejure/blob/master/src/snakejure/client.clj#L77). 

Does it help with what you are trying to achieve?

**Comment by lspector** [comment]
Very helpful -- thank you!

I've begun by tinkering with the first project I listed above, and it looks promising except for some reason I don't see results of calls to `q/text`, although I do see results of calls to `q/ellipse`, and from `println` calls it does look like the atom is being updated appropriately. Is there some default of `q/text` that might be responsible for this?

**Comment by nbeloglazov** [comment]
By default text color is white I believe. Try setting color to black before printing:

```clojure
(defn draw[]
  (q/background 255)
  (q/fill 0)
  ; Drawing progress as text
  (q/text "Hello, world" 100 100))
```

**Comment by lspector** [comment]
Beautiful -- that worked.

My problems are now solved, and I look forward to incorporating Quil into many projects for which I would have previously ruled it out, because I couldn't figure out how to use it in conjunction with projects that have their own overarching control structure.

I am really looking forward to this!

It would be great if the advice/code given here can be linked in some obvious way to quil.info, so that will be evident to new-comers. If my experience is any guide, many others (especially students) run into this issue and get stuck.

**Comment by marco-m** [comment]
hello @lspector, thanks for having asked this question, I think that @nbeloglazov answer will help a lot of people (me included!)

**Comment by lspector** [comment]
Thanks @marco-m! FWIW I have now used @nbeloglazov's answer to add a basic visualization capability to [Clojush](https://github.com/lspector/Clojush), which will produce something like the following to show the progress of evolution (this image was produced by a run of `lein run clojush.problems.demos.simple-regression :parent-selection :lexicase :visualize true`).

<img width="1000" alt="screen shot 2018-06-06 at 9 40 53 pm" src="https://user-images.githubusercontent.com/246808/41121939-dc6d9b7c-6a67-11e8-91e9-3b288cbc7f9c.png">

**Comment by nbeloglazov** [comment]
As Lee suggested, added a wiki article describing this approach with examples: [article](https://github.com/quil/quil/wiki/How-to-embed-Quil-in-another-program), [progress bar example](http://quil.info/sketches/show/307274905965be88d1658c21d70705ee292e556176ecddeca0e922a9f74d379f). Hopefully it'll be discoverable enough (two clicks from http://quil.info instead of one). 

Lee, thanks for bringing up this issue!
