### ISSUE TITLE
Can't disable smoothing on manually-created image

### ISSUE THREAD

**Issue by tkocmathla** [quil/quil#265]
I'm trying to draw a pixel art image using the pixels array, then scale it up using q/resize. I don't want smoothing for this (so it still looks like pixel art), but the no-smooth fn doesn't disable smoothing in this case. I tried different renderers as well as using (q/smooth 0), but nothing seems to work. Is this a supported use case for no-smooth? Is there another way I can do this?

Here's a minimal example:
```clojure
(q/sketch
  :size [128 128]
  :setup #(q/no-loop)
  :settings #(q/no-smooth)
  :draw (fn []
          (let [img (q/create-image 8 8 :rgb)
                pxs (q/pixels img)]
            (dotimes [i (* 8 8)]
              (aset-int pxs i (q/color (rand-int 256) (rand-int 256) (rand-int 256))))
            (q/update-pixels img)
            (q/resize img 128 128)
            (q/image img 0 0))))
```

**Comment by nbeloglazov** [comment]
Actually `no-smooth` has a bug in clojure version at the moment: it uses current-graphics and should use current-applet [here](https://github.com/quil/quil/blob/master/src/cljc/quil/core.cljc#L2670) because during settings there is no graphics yet.

But even after I fixed it locally I still get smoothed picture. I feel like no-smooth affects drawn figures like ellipse and not for resizing images.

As workaround you could probably implement scaling itself: function that takes array of pixel colors and size of each pixel and draws them.
