### ISSUE TITLE
How to compare image pixel color (q/get-pixel) to a reference color (q/color) in CLJS

### ISSUE THREAD

**Issue by gamecubate** [quil/quil#313]
In CLJS, what would be the most efficient way to compare an image's pixel color as returned by `q/get-pixel [im x y]` to some reference color created with the `q/color [r g b a]` function?

Reason for asking: current test fails as pixel color and ref color [alphas?] are expressed very differently, according to println:
```
(def ref-color (q/color 255 255 255 255))
(println :ref-color ref-color :pixel-color (q/get-pixel image 0 0))
```

```
:ref-color #object[Object rgba(255,255,255,1)]
:pixel-color #js [255 255 255 255]
```

**Comment by gamecubate** [comment]
This is what I have so far:
```
(if (= (seq (.-levels ref-color)) (seq (q/get-pixel img 0 0)))
   ;; do something
```

It's slow. Will see if I can optimize, for lack of a better way.

**Comment by nbeloglazov** [comment]
I don't know of a good solution. I think what you proposed is the best. Though maybe it's possible to compare `levels` and pixel as JS arrays instead of converting them to seq.  Maybe converting them to string is faster though still feels wasteful. I guess you could write function that takes simple array and uses native `.every()` method over one of them and check that value equals to the same value in the second array.

**Comment by gamecubate** [comment]
Thanks. Will leave this issue open until I've posted the solution/code.
