### ISSUE TITLE
Unable to use `pixel-density`

### ISSUE THREAD

**Issue by saneef** [quil/quil#332]
I'm unable to set pixel density on macOS (retina display).

```clojure
(q/defsketch random-sketch
  ; ...
  :settings #(q/pixel-density (q/display-density))
  ; ...
```

`(q/display-density)` return `1`. 

If I try `(q/display-density 2)`, I'm getting the error `pixelDensity(2) is not available for this display`.

I'm using `quil "3.1.0"`.

**Comment by cfdrake** [comment]
Hmm, I'm running into the same issue 😕 

Software:
- OpenJDK 1.8.0_252
- quil 3.1.0
- macOS Catalina 10.15.4 (19E287)

Hardware:
- MacBook Pro (Retina, 13-inch, Early 2015)

Interestingly, I don't have any issues with `pixelDensity(2)` in Processing (v3.5.4).

**Comment by bdevel** [comment]
This happened to me when I switched from Oracle JVM to OpenJDK. Unfortunately, I'd rather stick with OpenJDK 1.8 and may end up switching to Electron+WebGL. I suspect Processing is ships with it's own JVM which is why `pixelDensity` works there. Also, upgrading to a more recent OpenJDK breaks some of the Quil dependencies so not an option.

**Comment by cfdrake** [comment]
👍 Gotcha, thanks! Verified everything is working on Oracle JVM 1.8.
