### ISSUE TITLE
Unable to clone the repository

### ISSUE THREAD

**Issue by danielabajirov** [quil/quil#345]
Hello, im unable to clone this repository using github. 
![image](https://user-images.githubusercontent.com/33493609/105836753-f2b7d380-5fcd-11eb-94cf-2cfe53a5b311.png)
As you can see this file has an unvalid path.

**Comment by aviad** [comment]
@danielabajirov - can you please list the details of you environment (OS, versions, etc.) and the steps you followed in trying to clone this repo?

**Comment by dgtized** [comment]
I just fixed this: https://github.com/quil/quil/pull/395/commits/2f392c05fb0ee3610e6abf760a8deb4b507a4613. On windows, filenames cannot contain the character `?`. This was one of the problems blocking the CI system from running tests on windows. That is now fixed in HEAD, but not yet part of the released version.
